# Problem Set 2

In [16]:
# Imports 

import sympy as sp
import numpy as np
from scipy.linalg import lu

Section 2.5

24.

In [15]:
# Perform Gauss Jordan elimination 
# Here U * U^-1 = I
# We need to find U^-1

def gauss_jordan_elimination(matrix):
    """
    Perform Gauss-Jordan elimination on the given matrix.
    """
    rows, cols = matrix.shape
    matrix = matrix.applyfunc(sp.simplify)

    for i in range(rows):
        # Make the diagonal contain all 1s
        if matrix[i,i] == 0:
            for k in range(i+1, rows):
                if matrix[k,i] != 0:
                    matrix.row_swap(i, k)
                    break
        # Normalize the pivot row
        matrix[i] = matrix[i] / matrix[i,i]

        # Make all the rows above and below the pivot 0
        for j in range(rows):
            if j != i:
                matrix[j, :] -= matrix[i, :] * matrix[j, i]
                matrix = matrix.applyfunc(sp.simplify)

    return matrix

def gauss_jordan_inverse(A):
    """ Returns the inverse of matrix A using Gauss-Jordan elimination """
    n = A.shape[0]

    # Augment with the identity matrix
    aug = A.row_join(sp.eye(n))

    # Perform Gauss-Jordan elimination
    rref = gauss_jordan_elimination(aug)

    # Extract the inverse from the augmented matrix
    inverse = rref[:, n:]

    return inverse

a, b, c = sp.symbols('a b c')
U = sp.Matrix([[1, a, b], [0, 1, c], [0, 0, 1]])
U_inv = gauss_jordan_inverse(U)

sp.pprint(U_inv)

⎡1  -a  a⋅c - b⎤
⎢              ⎥
⎢0  1     -c   ⎥
⎢              ⎥
⎣0  0      1   ⎦


Section 2.6

13.


In [14]:
a, b, c, d = sp.symbols('a b c d')

A = sp.Matrix([[a, a, a, a], [a, b, b, b], [a, b, c, c], [a, b, c, d]])

L, U, P = A.LUdecomposition()

print("Marix A:")
sp.pprint(A)
print("Matrix L:")
sp.pprint(L)
print("Matrix U:")
sp.pprint(U)

reconstructed = L * U
print("Reconstructed Matrix:")
sp.pprint(reconstructed)

print("\nIs A == L * U?")
print(A.equals(reconstructed))

Marix A:
⎡a  a  a  a⎤
⎢          ⎥
⎢a  b  b  b⎥
⎢          ⎥
⎢a  b  c  c⎥
⎢          ⎥
⎣a  b  c  d⎦
Matrix L:
⎡1  0  0  0⎤
⎢          ⎥
⎢1  1  0  0⎥
⎢          ⎥
⎢1  1  1  0⎥
⎢          ⎥
⎣1  1  1  1⎦
Matrix U:
⎡a    a       a       a   ⎤
⎢                         ⎥
⎢0  -a + b  -a + b  -a + b⎥
⎢                         ⎥
⎢0    0     -b + c  -b + c⎥
⎢                         ⎥
⎣0    0       0     -c + d⎦
Reconstructed Matrix:
⎡a  a  a  a⎤
⎢          ⎥
⎢a  b  b  b⎥
⎢          ⎥
⎢a  b  c  c⎥
⎢          ⎥
⎣a  b  c  d⎦

Is A == L * U?
True


Section 2.6

25.

Ans : 
$
(L^{-1})_{i,j} =
\begin{cases} 
\frac{j}{i}, & \text{if } j \leq i \\
0, & \text{if } j > i
\end{cases}
$

In [18]:
# Define the 6x6 tridiagonal matrix K
K = np.array([[ 2, -1,  0,  0,  0,  0],
              [-1,  2, -1,  0,  0,  0],
              [ 0, -1,  2, -1,  0,  0],
              [ 0,  0, -1,  2, -1,  0],
              [ 0,  0,  0, -1,  2, -1],
              [ 0,  0,  0,  0, -1,  2]])

P, L, U = lu(K)
L_inv = np.linalg.inv(L)

print("Matrix K:")
print(K)
print("\nLower Triangular Matrix L:")
print(L)
print("\nUpper Triangular Matrix U:")
print(U)
print("\nInverse of L (L^(-1)):")
print(L_inv)

Matrix K:
[[ 2 -1  0  0  0  0]
 [-1  2 -1  0  0  0]
 [ 0 -1  2 -1  0  0]
 [ 0  0 -1  2 -1  0]
 [ 0  0  0 -1  2 -1]
 [ 0  0  0  0 -1  2]]

Lower Triangular Matrix L:
[[ 1.          0.          0.          0.          0.          0.        ]
 [-0.5         1.          0.          0.          0.          0.        ]
 [ 0.         -0.66666667  1.          0.          0.          0.        ]
 [ 0.          0.         -0.75        1.          0.          0.        ]
 [ 0.          0.          0.         -0.8         1.          0.        ]
 [ 0.          0.          0.          0.         -0.83333333  1.        ]]

Upper Triangular Matrix U:
[[ 2.         -1.          0.          0.          0.          0.        ]
 [ 0.          1.5        -1.          0.          0.          0.        ]
 [ 0.          0.          1.33333333 -1.          0.          0.        ]
 [ 0.          0.          0.          1.25       -1.          0.        ]
 [ 0.          0.          0.          0.          1.2  

26.

In [20]:
K_inv = np.linalg.inv(K)
print("\nInverse of K * 7:")
print(K_inv * 7)

M = np.array([
    [6, 5, 4, 3, 2, 1], 
    [5, 10, 8, 6, 4, 2],
    [4, 8, 12, 9, 6, 3],
    [3, 6, 9, 12, 8, 4],
    [2, 4, 6, 8, 10, 5],
    [1, 2, 3, 4, 5, 6]
])

Res = K @ M
print("\nMatrix Res:")
print(Res)


Inverse of K * 7:
[[ 6.  5.  4.  3.  2.  1.]
 [ 5. 10.  8.  6.  4.  2.]
 [ 4.  8. 12.  9.  6.  3.]
 [ 3.  6.  9. 12.  8.  4.]
 [ 2.  4.  6.  8. 10.  5.]
 [ 1.  2.  3.  4.  5.  6.]]

Matrix Res:
[[7 0 0 0 0 0]
 [0 7 0 0 0 0]
 [0 0 7 0 0 0]
 [0 0 0 7 0 0]
 [0 0 0 0 7 0]
 [0 0 0 0 0 7]]
